client:
  version: 1.0.0
  api_server_base_uri: http://localhost:3000
server:
  api_server_base_uri: http://localhost:3000
  battle_server_base_uri: ws://localhost:5000
  database:
    host: localhost
    port: 3306
    user: root
    password: ''
build:
  product_name: Foo
  bundle_identifier: com.example.foo
  ios:
    code_sign_identity: "iPhone Distribution: John Doe (XXXXXXXXXX)"
    provisioning_profile: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    export_options: # See xcodebuild -h
      method: ad-hoc
