client:
  version: 1.0.0
  api_server_base_uri: http://localhost:3000
server:
  api_server_base_uri: http://localhost:3000
  battle_server_base_uri: ws://localhost:5000
build:
  product_name: Foo
  bundle_identifier: com.example.foo
  ios:
    code_sign_identity: "iPhone Developer: John Doe (XXXXXXXXXX)"
    provisioning_profile: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
